module Backend.X86_64Spec (x86_64Tests) where

import Rune.AST.Parser (parseRune)
import Rune.Backend.X86_64.Codegen (emitAssembly)
import Rune.IR.Generator (generateIR)
import Rune.Lexer.Lexer (lexer)
import Test.Tasty (TestTree, testGroup)
import Test.Tasty.HUnit (testCase, (@?=))
import Text.Megaparsec (errorBundlePretty)

--
-- public
--

x86_64Tests :: TestTree
x86_64Tests =
  testGroup
    "Rune.Backend.x86_64Spec"
    [ testCase "x86_64 Test Programs" x86_64TestShowString,
      testCase "x86_64 If-Else Test" x86_64TestIfElse,
      testCase "x86_64 Loop Example Test" x86_64TestLoopExample,
      testCase "x86_64 Types Test" x86_64TestTypes
    ]

--
-- private
--

runX86_64 :: String -> String
runX86_64 source =
  case lexer "test" source of
    Left err -> error $ errorBundlePretty err
    Right tokens -> case parseRune "test" tokens of
      Left err -> error err
      Right ast -> emitAssembly $ generateIR ast

--
-- test programs
--

x86_64TestShowString :: IO ()
x86_64TestShowString = do
  let program =
        unlines
          [ "def show_string(str: string) -> null",
            "{",
            "    for c in str {",
            "        show(c);",
            "    }",
            "}",
            "",
            "def get_string() -> string",
            "{",
            "    return \"Hello, Rune!\n\";",
            "}",
            "",
            "def main() -> null",
            "{",
            "    str: string = get_string();",
            "",
            "    show_string(str);",
            "}",
            ""
          ]

      expected =
        unlines
          [ "extern putchar",
            "section .data",
            "str_get_string0 db \"Hello, Rune!\",10, 0",
            "section .text",
            "global main",
            "main:",
            "    push rbp",
            "    mov rbp, rsp",
            "    sub rsp, 16",
            "    call get_string",
            "    mov dword [rbp-8], eax",
            "    movsxd rdi, dword [rbp-8]",
            "    call show_string",
            "    mov dword [rbp-4], eax",
            "    xor rax, rax",
            "    jmp .L.function_end_main",
            ".L.function_end_main:",
            "    mov rsp, rbp",
            "    pop rbp",
            "    ret",
            "",
            "global get_string",
            "get_string:",
            "    push rbp",
            "    mov rbp, rsp",
            "    sub rsp, 16",
            "    mov rax, str_get_string0",
            "    mov qword [rbp-8], rax",
            "    mov rax, qword [rbp-8]",
            "    jmp .L.function_end_get_string",
            ".L.function_end_get_string:",
            "    mov rsp, rbp",
            "    pop rbp",
            "    ret",
            "",
            "global show_string",
            "show_string:",
            "    push rbp",
            "    mov rbp, rsp",
            "    sub rsp, 32",
            "    mov qword [rbp-8], rdi",
            "    mov rax, qword [rbp-8]",
            "    mov qword [rbp-16], rax",
            ".L.loop_header0:",
            "    mov rax, qword [rbp-16]",
            "    movzx rax, byte [rax]",
            "    mov byte [rbp-24], al",
            ".L.loop_check0:",
            "    mov al, byte [rbp-24]",
            "    test al, al",
            "    je .L.loop_end0",
            ".L.body0:",
            "    movzx rdi, byte [rbp-24]",
            "    call putchar",
            "    add qword [rbp-16], 1",
            "    jmp .L.loop_header0",
            ".L.loop_end0:",
            "    xor rax, rax",
            "    jmp .L.function_end_show_string",
            ".L.function_end_show_string:",
            "    mov rsp, rbp",
            "    pop rbp",
            "    ret",
            ""
          ]

  runX86_64 program @?= expected

x86_64TestIfElse :: IO ()
x86_64TestIfElse = do
  let program =
        unlines
          [ "def main() -> i32 {",
            "    a: i32 = 5;",
            "",
            "    if a < 10 {",
            "        show(\"a is less than 10\\n\");",
            "    } else {",
            "        show(\"a is 10 or greater\\n\");",
            "    }",
            "    return a;",
            "}"
          ]

      expected =
        unlines
          [ "extern printf",
            "section .data",
            "str_main1 db \"a is 10 or greater\",10, 0",
            "str_main0 db \"a is less than 10\",10, 0",
            "section .text",
            "global main",
            "main:",
            "    push rbp",
            "    mov rbp, rsp",
            "    sub rsp, 32",
            "    mov dword [rbp-28], 5",
            "    mov eax, dword [rbp-28]",
            "    mov rbx, 10",
            "    cmp rax, rbx",
            "    setl al",
            "    movzx eax, al",
            "    mov dword [rbp-4], eax",
            "    mov eax, dword [rbp-4]",
            "    test eax, eax",
            "    je .L.else0",
            "    mov rax, str_main0",
            "    mov qword [rbp-20], rax",
            "    mov rdi, qword [rbp-20]",
            "    call printf",
            "    jmp .L.end0",
            ".L.else0:",
            "    mov rax, str_main1",
            "    mov qword [rbp-12], rax",
            "    mov rdi, qword [rbp-12]",
            "    call printf",
            ".L.end0:",
            "    mov eax, dword [rbp-28]",
            "    jmp .L.function_end_main",
            ".L.function_end_main:",
            "    mov rsp, rbp",
            "    pop rbp",
            "    ret",
            ""
          ]
  runX86_64 program @?= expected

x86_64TestLoopExample :: IO ()
x86_64TestLoopExample = do
  let program =
        unlines
          [ "def pretty_show(value: i32) -> null",
            "{",
            "    show(\"The final value is: \");",
            "    show(value);",
            "    show(\'\\n\');",
            "}",
            "",
            "def loops() -> i32",
            "{",
            "    k: i32;",
            "",
            "    for i = 0 to 10 {",
            "        ++i;",
            "    }",
            "",
            "    loop {",
            "        k += 2;",
            "        if k > 10 {",
            "            stop;",
            "        }",
            "    }",
            "    k",
            "}",
            "",
            "def main() -> null",
            "{",
            "    pretty_show(loops());",
            "}",
            ""
          ]
      expected =
        unlines
          [ "extern printf",
            "extern putchar",
            "section .data",
            "str_pretty_show1 db \"%d\", 0",
            "str_pretty_show0 db \"The final value is: \", 0",
            "section .text",
            "global main",
            "main:",
            "    push rbp",
            "    mov rbp, rsp",
            "    sub rsp, 16",
            "    call loops",
            "    mov dword [rbp-8], eax",
            "    movsxd rdi, dword [rbp-8]",
            "    call pretty_show",
            "    mov dword [rbp-4], eax",
            "    xor rax, rax",
            "    jmp .L.function_end_main",
            ".L.function_end_main:",
            "    mov rsp, rbp",
            "    pop rbp",
            "    ret",
            "",
            "global loops",
            "loops:",
            "    push rbp",
            "    mov rbp, rsp",
            "    sub rsp, 32",
            "    mov dword [rbp-12], 0",
            "    mov dword [rbp-16], 0",
            ".L.loop_header0:",
            "    mov eax, dword [rbp-16]",
            "    mov rbx, 10",
            "    cmp rax, rbx",
            "    setl al",
            "    movzx eax, al",
            "    mov dword [rbp-20], eax",
            "    mov eax, dword [rbp-20]",
            "    test eax, eax",
            "    je .L.loop_end0",
            ".L.body0:",
            "    add qword [rbp-16], 1",
            "    jmp .L.loop_header0",
            ".L.loop_end0:",
            ".L.loop_header1:",
            "    mov eax, dword [rbp-12]",
            "    mov rbx, 2",
            "    add rax, rbx",
            "    mov dword [rbp-8], eax",
            "    mov eax, dword [rbp-8]",
            "    mov dword [rbp-12], eax",
            "    mov eax, dword [rbp-12]",
            "    mov rbx, 10",
            "    cmp rax, rbx",
            "    setg al",
            "    movzx eax, al",
            "    mov dword [rbp-4], eax",
            "    mov eax, dword [rbp-4]",
            "    test eax, eax",
            "    je .L.end2",
            "    jmp .L.loop_end1",
            ".L.end2:",
            "    jmp .L.loop_header1",
            ".L.loop_end1:",
            "    mov eax, dword [rbp-12]",
            "    jmp .L.function_end_loops",
            ".L.function_end_loops:",
            "    mov rsp, rbp",
            "    pop rbp",
            "    ret",
            "",
            "global pretty_show",
            "pretty_show:",
            "    push rbp",
            "    mov rbp, rsp",
            "    sub rsp, 32",
            "    mov dword [rbp-4], edi",
            "    mov rax, str_pretty_show0",
            "    mov qword [rbp-12], rax",
            "    mov rdi, qword [rbp-12]",
            "    call printf",
            "    mov rax, str_pretty_show1",
            "    mov qword [rbp-20], rax",
            "    mov rdi, qword [rbp-20]",
            "    movsxd rsi, dword [rbp-4]",
            "    call printf",
            "    mov rdi, 10",
            "    call putchar",
            "    xor rax, rax",
            "    jmp .L.function_end_pretty_show",
            ".L.function_end_pretty_show:",
            "    mov rsp, rbp",
            "    pop rbp",
            "    ret",
            ""
          ]

  runX86_64 program @?= expected

x86_64TestTypes :: IO ()
x86_64TestTypes = do
  let program =
        unlines
          [ "def main() -> null",
            "{",
            "    b: bool   = true;",
            "    a8:  i8   = -8;",
            "    a16: i16  = -1600;",
            "    a32: i32  = -32000;",
            "    a64: i64  = -6400000000;",
            "",
            "    u8v:  u8  = 8;",
            "    u16v: u16 = 1600;",
            "    u32v: u32 = 32000;",
            "    u64v: u64 = 6400000000;",
            "",
            "    s: string = \"Types test\\n\";",
            "",
            "    show(\"bool: \");  show(b);   show('\\n');",
            "    show(\"i8: \");    show(a8);  show('\\n');",
            "    show(\"i16: \");   show(a16); show('\\n');",
            "    show(\"i32: \");   show(a32); show('\\n');",
            "    show(\"i64: \");   show(a64); show('\\n');",
            "",
            "    show(\"u8: \");    show(u8v);  show('\\n');",
            "    show(\"u16: \");   show(u16v); show('\\n');",
            "    show(\"u32: \");   show(u32v); show('\\n');",
            "    show(\"u64: \");   show(u64v); show('\\n');",
            "",
            "    show(\"string: \"); show(s);",
            "}"
          ]

  let expected =
        unlines
          [ "extern printf",
            "extern putchar",
            "section .data",
            "str_main18 db \"string: \", 0",
            "str_main17 db \"%lu\", 0",
            "str_main16 db \"u64: \", 0",
            "str_main15 db \"%u\", 0",
            "str_main14 db \"u32: \", 0",
            "str_main13 db \"%hu\", 0",
            "str_main12 db \"u16: \", 0",
            "str_main11 db \"u8: \", 0",
            "str_main10 db \"%ld\", 0",
            "str_main9 db \"i64: \", 0",
            "str_main8 db \"%d\", 0",
            "str_main7 db \"i32: \", 0",
            "str_main6 db \"%hd\", 0",
            "str_main5 db \"i16: \", 0",
            "str_main4 db \"%hhd\", 0",
            "str_main3 db \"i8: \", 0",
            "str_main2 db \"%d\", 0",
            "str_main1 db \"bool: \", 0",
            "str_main0 db \"Types test\",10, 0",
            "section .text",
            "global main",
            "main:",
            "    push rbp",
            "    mov rbp, rsp",
            "    sub rsp, 208",
            "    mov byte [rbp-176], 1",
            "    mov byte [rbp-177], -8",
            "    mov word [rbp-193], -1600",
            "    mov dword [rbp-189], -32000",
            "    mov rax, -6400000000",
            "    mov qword [rbp-185], rax",
            "    mov byte [rbp-1], 8",
            "    mov word [rbp-17], 1600",
            "    mov dword [rbp-13], 32000",
            "    mov rax, 6400000000",
            "    mov qword [rbp-9], rax",
            "    mov rax, str_main0",
            "    mov qword [rbp-105], rax",
            "    mov rax, str_main1",
            "    mov qword [rbp-97], rax",
            "    mov rdi, qword [rbp-97]",
            "    call printf",
            "    mov rax, str_main2",
            "    mov qword [rbp-137], rax",
            "    mov rdi, qword [rbp-137]",
            "    movzx rsi, byte [rbp-176]",
            "    call printf",
            "    mov rdi, 10",
            "    call putchar",
            "    mov rax, str_main3",
            "    mov qword [rbp-49], rax",
            "    mov rdi, qword [rbp-49]",
            "    call printf",
            "    mov rax, str_main4",
            "    mov qword [rbp-129], rax",
            "    mov rdi, qword [rbp-129]",
            "    movsx rsi, byte [rbp-177]",
            "    call printf",
            "    mov rdi, 10",
            "    call putchar",
            "    mov rax, str_main5",
            "    mov qword [rbp-41], rax",
            "    mov rdi, qword [rbp-41]",
            "    call printf",
            "    mov rax, str_main6",
            "    mov qword [rbp-121], rax",
            "    mov rdi, qword [rbp-121]",
            "    movsx rsi, word [rbp-193]",
            "    call printf",
            "    mov rdi, 10",
            "    call putchar",
            "    mov rax, str_main7",
            "    mov qword [rbp-33], rax",
            "    mov rdi, qword [rbp-33]",
            "    call printf",
            "    mov rax, str_main8",
            "    mov qword [rbp-113], rax",
            "    mov rdi, qword [rbp-113]",
            "    movsxd rsi, dword [rbp-189]",
            "    call printf",
            "    mov rdi, 10",
            "    call putchar",
            "    mov rax, str_main9",
            "    mov qword [rbp-25], rax",
            "    mov rdi, qword [rbp-25]",
            "    call printf",
            "    mov rax, str_main10",
            "    mov qword [rbp-169], rax",
            "    mov rdi, qword [rbp-169]",
            "    mov rsi, qword [rbp-185]",
            "    call printf",
            "    mov rdi, 10",
            "    call putchar",
            "    mov rax, str_main11",
            "    mov qword [rbp-89], rax",
            "    mov rdi, qword [rbp-89]",
            "    call printf",
            "    movzx rdi, byte [rbp-1]",
            "    call putchar",
            "    mov rdi, 10",
            "    call putchar",
            "    mov rax, str_main12",
            "    mov qword [rbp-81], rax",
            "    mov rdi, qword [rbp-81]",
            "    call printf",
            "    mov rax, str_main13",
            "    mov qword [rbp-161], rax",
            "    mov rdi, qword [rbp-161]",
            "    movzx rsi, word [rbp-17]",
            "    call printf",
            "    mov rdi, 10",
            "    call putchar",
            "    mov rax, str_main14",
            "    mov qword [rbp-73], rax",
            "    mov rdi, qword [rbp-73]",
            "    call printf",
            "    mov rax, str_main15",
            "    mov qword [rbp-153], rax",
            "    mov rdi, qword [rbp-153]",
            "    mov esi, dword [rbp-13]",
            "    call printf",
            "    mov rdi, 10",
            "    call putchar",
            "    mov rax, str_main16",
            "    mov qword [rbp-65], rax",
            "    mov rdi, qword [rbp-65]",
            "    call printf",
            "    mov rax, str_main17",
            "    mov qword [rbp-145], rax",
            "    mov rdi, qword [rbp-145]",
            "    mov rsi, qword [rbp-9]",
            "    call printf",
            "    mov rdi, 10",
            "    call putchar",
            "    mov rax, str_main18",
            "    mov qword [rbp-57], rax",
            "    mov rdi, qword [rbp-57]",
            "    call printf",
            "    mov rdi, qword [rbp-105]",
            "    call printf",
            "    xor rax, rax",
            "    jmp .L.function_end_main",
            ".L.function_end_main:",
            "    mov rsp, rbp",
            "    pop rbp",
            "    ret",
            ""
          ]

  runX86_64 program @?= expected
